[build]
executable_name = "esf"
command = "python $dumb_project_dir/esf.py"
excluded = [
  ".gitignore",
  "__pycache__",
  "images",
  "keyboard/__pycache__",
  ".ruff_cache",
  "dumb_build.toml",
  "test.py",
  "LICENSE",
  "README.md",
]
local_install_excluded = [".git"]
